Project/Rails_Proj/Hospital_Management/config/routes.rb
Rails.application.routes.draw do
  get "login", to:"session#new", as: "doctor_login"
  post "login", to:"session#create"
  get "logout", to: "session#log_out", as: "doctor_logout"

  get 'department/show'
  root 'department#show'
  # get 'hospital/soft_delete/:id' =>'hospital#soft_delete'
  get "patient/:id/soft_delete", to:"patient#soft_delete", as: "patient_soft_delete"
  get "doctors/paginate", to:"doctors#paginate", as:"doctor_paginate"
  namespace :api do
    namespace :v1 do
      resources :doctors
      resources :hospital
      post 'doctor/login', to: 'session#login'
    end
  end
  resources :hospital, :doctors, :patient, :department, :appointments

end

Project/Rails_Proj/Hospital_Management/app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :hospital

  has_many :appointments
  has_many :doctors , through: :appointments

  has_many :medical_records

  scope :not_deleted, -> { where(deleted: false) }
  scope :deleted, -> { where(deleted: true) }

  # #create the soft delete method
  # def soft_delete
  #   update(deleted: true)
  # end
  #
  # # make an undelete method
  # def undelete
  #   update(deleted: false)
  # end
end

Project/Rails_Proj/Hospital_Management/app/controllers/patient_controller.rb
class PatientController < ApplicationController
  def new
    @patient = Patient.new
  end

  def index
    @patient = Patient.all.order(created_at: :desc)
  end

  def show
    @patient = Patient.find_by(id: params[:id])
  end


  def create
    patient = Patient.new patient_params
    patient.save
    redirect_to patient_index_path
  end

  def edit
    @patient = Patient.find_by(id: params[:id])
  end

  def update
      patient = Patient.find_by(id: params[:id])
      patient.update patient_params
      redirect_to patient_index_path
  end

  def destroy
    patient = Patient.find_by(id: params[:id])
    patient.destroy
    redirect_to patient_index_path
  end

  def soft_delete
    @patient = Patient.find_by(id: params[:id])
    if @patient.deleted
      @patient.update(deleted: false)
    else
      @patient.update(deleted: true)
    end
    redirect_to patient_index_path
  end

  def patient_params
    params.require(:patient).permit(:First_Name,:Last_Name,:age,:Address,:Mobile,:Gender,:hospital_id)
  end

end

Project/Rails_Proj/Hospital_Management/app/helpers/patient_helper.rb
module PatientHelper
end

Project/Rails_Proj/Hospital_Management/app/views/patient/edit.html.erb
    <h1><center>Edit Patient Information</center></h1>
      <%= form_for @patient do |h| %>
      <p>
        <%= h.label :First_Name %><br>
        <%= h.text_field :First_Name %>
      </p>

      <p>
        <%= h.label :Last_Name %><br>
        <%= h.text_field :Last_Name %>
      </p>

      <p>
        <%= h.label :Age %><br>
        <%= h.text_field :age %>
      </p>

      <p>
        <%= h.label :Address %><br>
        <%= h.text_field :Address %>
      </p>

      <p>
        <%= h.label :Mobile %><br>
        <%= h.text_field :Mobile %>
      </p>

      <p>
        <%= h.label :Gender %><br>
        <%= h.text_field :Gender %>
      </p>

      <p>
        <%= h.label :Hospital_id %><br>
        <%= h.text_field :hospital_id %>
      </p>

      <p>
        <%= h.submit%>
      </p>
    <% end %>

Project/Rails_Proj/Hospital_Management/app/views/patient/index.html.erb
<table>
  <h1><strong><center>Patient Details</center></strong></h1>
  <tr><%= link_to 'New' , new_patient_path %></tr>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Age</th>
    <th>Address</th>
    <th>Mobile</th>
    <th>Gender</th>
    <th>Hospital Id</th>
    <th>Show</th>
    <th>Edit</th>
    <th>Delete</th>
    <th>soft_delete</th>
  </tr>
  <% @patient.each do |h| %>
  <tr>
      <td><%= h.First_Name %></td>
      <td><%= h.Last_Name %></td>
      <td><%= h.age %></td>
      <td><%= h.Address %></td>
      <td><%= h.Mobile %></td>
      <td><%= h.Gender %></td>
      <td><%= h.hospital_id %></td>
      <td><%= link_to 'Show' , patient_path(h)%></td>
      <td><%= link_to 'Edit' , edit_patient_path(h)%></td>
      <td><%= link_to 'Delete' , patient_path(h) , method: :delete, data: {confirm: 'Are you sure?'}%></td>
      <td><%= link_to  h.deleted ? 'Restore' : 'Soft Delete' , patient_soft_delete_path(h)%></td>
  </tr>
  <% end %>
</table>

Project/Rails_Proj/Hospital_Management/app/views/patient/new.html.erb
    <h1><center>Patient Information</center></h1>
      <%= form_for @patient, url: patient_index_url do |h| %>
      <p>
        <%= h.label :First_Name %><br>
        <%= h.text_field :First_Name %>
      </p>

      <p>
        <%= h.label :Last_Name %><br>
        <%= h.text_field :Last_Name %>
      </p>

      <p>
        <%= h.label :Age %><br>
        <%= h.text_field :age %>
      </p>

      <p>
        <%= h.label :Address %><br>
        <%= h.text_field :Address %>
      </p>

      <p>
        <%= h.label :Mobile %><br>
        <%= h.text_field :Mobile %>
      </p>

      <p>
        <%= h.label :Gender %><br>
        <%= h.text_field :Gender %>
      </p>

      <p>
        <%= h.label :Hospital_id %><br>
        <%= h.text_field :hospital_id %>
      </p>

      <p>
        <%= h.submit%>
      </p>
    <% end %>

Project/Rails_Proj/Hospital_Management/app/views/patient/show.html.erb
<%= @patient.First_Name %><br>
<%= @patient.Last_Name %><br>