Project/Rails_Proj/Hospital_Management/config/routes.rb
Rails.application.routes.draw do
  get "login", to:"session#new", as: "doctor_login"
  post "login", to:"session#create"
  get "logout", to: "session#log_out", as: "doctor_logout"

  get 'department/show'
  root 'department#show'
  # get 'hospital/soft_delete/:id' =>'hospital#soft_delete'
  get "patient/:id/soft_delete", to:"patient#soft_delete", as: "patient_soft_delete"
  get "doctors/paginate", to:"doctors#paginate", as:"doctor_paginate"
  namespace :api do
    namespace :v1 do
      resources :doctors
      resources :hospital
      post 'doctor/login', to: 'session#login'
    end
  end
  resources :hospital, :doctors, :patient, :department, :appointments

end

Project/Rails_Proj/Hospital_Management/app/models/hospital.rb
class Hospital < ApplicationRecord
  has_many :patients
  has_many :doctors
  accepts_nested_attributes_for :doctors
end

Project/Rails_Proj/Hospital_Management/app/controllers/Api/V1/hospital_controller.rb
module Api
  module V1
    class HospitalController < CustomController
      def index
        @hospitals = Hospital.all
        render json: {status: "Successfull", message: 'Index action is successfull', doctors: ActiveModel::Serializer::CollectionSerializer.new(@hospitals, each_serializer: HospitalSerializer)} ,adapter: :json
      end

      def show
        @hospital = Hospital.find_by(id: params[:id])
        render json: @hospital ,adapter: :json
      end

      def create
        @hospital = Hospital.new hospital_params
        if @hospital.save
          render json: @hospitals ,adapter: :json, status: 200
        else
          render json: {error: 'Unable to create hospital'}, status: 422
        end
      end

      def update
        @hospital = Hospital.find_by(id: params[:id])
        if @hospital
          @hospital.update hospital_params
          render json: {message: 'Hospital successfully updated'}, status: 200
        else
          render json: {error: 'Unable to Update'}, status: 422
        end
      end

      def destroy
        @hospital = Hospital.find_by(id: params[:id])
        if @hospital
          @hospital.destroy
          render json: {message: 'Successfully destroyed'}, status: 200
        else
          render json: {error: 'Not destroyed'}, status: 400
        end
      end

      private
      def hospital_params
        params.permit(:Name , :Address , :State , :Beds)
      end

    end
  end
end

Project/Rails_Proj/Hospital_Management/app/controllers/hospital_controller.rb
class HospitalController < ApplicationController
  def index
    @hospital = Hospital.all
  end


  def show
    @hospital = Hospital.find_by(id: params[:id])
  end

  def new
    @hospital = Hospital.new
    2.times {@hospital.doctors.build}
  end

  def create
      hospital = Hospital.new hospital_params
      hospital.save
      redirect_to hospital_index_path
  end

  def edit
      @hospital = Hospital.find_by(id: params[:id])
  end

  def update
    @hospital = Hospital.find_by(id: params[:id])
    if @hospital.update hospital_params
      redirect_to hospital_index_path
    end
  end


  def hospital_params
    params.require(:hospital).permit(:Name , :Address , :State , :Beds ,doctors_attributes: [:first_name, :last_name, :password, :confirm_password])
  end

  def destroy
    hospital = Hospital.find_by(id: params[:id])
    hospital.destroy
    redirect_to hospital_index_path
  end
end

Project/Rails_Proj/Hospital_Management/app/helpers/hospital_helper.rb
module HospitalHelper
end

Project/Rails_Proj/Hospital_Management/app/views/hospital/edit.html.erb
    <h1><center>Update Hospital Information</center></h1>
      <%= form_for @hospital do |h| %>
      <p>
        <%= h.label :Hospital_Name %><br>
        <%= h.text_field :Name %>
      </p>

      <p>
        <%= h.label :Address %><br>
        <%= h.text_field :Address %>
      </p>

      <p>
        <%= h.label :State %><br>
        <%= h.text_field :State %>
      </p>

      <p>
        <%= h.label :Beds %><br>
        <%= h.text_field :Beds %>
      </p>

      <p>
        <%= h.submit%>
      </p>
    <% end %>

Project/Rails_Proj/Hospital_Management/app/views/hospital/index.html.erb
<table>
  <h1><strong><center>Hospital Details</center></strong></h1>
    <tr><%= link_to 'New' , new_hospital_path %></tr>
    <tr>
  <th>Name</th>
  <th>Address</th>
  <th>State</th>
  <th>Beds</th>
  <th>show</th>
  <th>Edit</th>
  <th>Delete</th>
  </tr>
  <% @hospital.each do |h| %>
  <tr>
      <td><%= h.Name %></td>
      <td><%= h.Address %></td>
      <td><%= h.State %></td>
      <td><%= h.Beds %></td>
      <td><%= link_to 'show' , hospital_path(h) %></td>
      <td><%= link_to 'edit' ,edit_hospital_path(h) %></td>
      <td><%= link_to 'delete' ,hospital_path(h) ,method: :delete ,data: {confirm: 'Are you certain?'} %></td>
  </tr>
  <% end %>
</table>

Project/Rails_Proj/Hospital_Management/app/views/hospital/new.html.erb
    <h1><center>Hospital Information</center></h1>
    <div class="container w-50 bg-dark text-white pb-1">
      <%= form_for @hospital,  url: hospital_index_url do |h| %>
      <div class="form-group">
        <%= h.label :Hospital_Name %><br>
        <%= h.text_field :Name ,class: "form-control" %>
      </div>

      <div class="form-group">
        <%= h.label :Address %><br>
        <%= h.text_field :Address ,class: "form-control"%>
      </div>


      <div class="form-group">
        <%= h.label :State %><br>
        <%= h.text_field :State ,class: "form-control" %>
      </div>

      <div class="form-group">
        <%= h.label :Beds %><br>
        <%= h.text_field :Beds ,class: "form-control" %>
      </div>
</div>
  <div class="container w-50 bg-dark text-white mt-5 pb-1">
      <h6>Create Doctors(Optional)</h6>
      <%= h.fields_for :doctors do |d|%>
        <li>
          <p>
            <%= d.label :First_name%>
            <%= d.text_field :first_name ,class: "form-control"%>
          </p>

          <p>
            <%= d.label :Last_name%>
            <%= d.text_field :last_name ,class: "form-control"%>
          </p>

          <p>
            <%= d.label :Password%>
            <%= d.password_field :password ,class: "form-control"%>
          </p>

          <p>
            <%= d.label :confirm_password%>
            <%= d.password_field :confirm_password ,class: "form-control"%>
          </p>
        </li>
        <% end %>

      <p>
        <%= h.submit class: "btn btn-primary"%>
      </p>
    <% end %>
</div>

Project/Rails_Proj/Hospital_Management/app/views/hospital/show.html.erb
<div class="bg-secondary text-white">
  <h1><strong><center>Login Doctor</center></strong></h1><hr>
</div>
  <div class="text-center font-weight-bold">
    Id: <%= @hospital.id %><br>
    Hospital Name: <%= @hospital.Name %><br>
    Address: <%= @hospital.Address %><br>
    State: <%= @hospital.State %><br>
    Beds: <%= @hospital.Beds %><br>
  </div>