Project/Rails_Proj/Hospital_Management/config/routes.rb
Rails.application.routes.draw do
  get "login", to:"session#new", as: "doctor_login"
  post "login", to:"session#create"
  get "logout", to: "session#log_out", as: "doctor_logout"

  get 'department/show'
  root 'department#show'
  # get 'hospital/soft_delete/:id' =>'hospital#soft_delete'
  get "patient/:id/soft_delete", to:"patient#soft_delete", as: "patient_soft_delete"
  get "doctors/paginate", to:"doctors#paginate", as:"doctor_paginate"
  namespace :api do
    namespace :v1 do
      resources :doctors
      resources :hospital
      post 'doctor/login', to: 'session#login'
    end
  end
  resources :hospital, :doctors, :patient, :department, :appointments

end

Project/Rails_Proj/Hospital_Management/app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments
  has_many :patients , through: :appointments
  belongs_to :hospital
  has_many :medical_records
  mount_uploader :avatar , AvatarUploader

  scope :next_page, ->(id){where("id = ?",id+1)  }
  # scope :deleted, -> { where(deleted: true) }

  # #create the soft delete method
  # def soft_delete
  #   update(deleted: true)
  # end
  #
  # # make an undelete method
  # def undelete
  #   update(deleted: false)
  # end

  # validates :First_name , :Last_name , format: {with: /\A[a-zA-Z]+\z/ ,message: 'Only alphabets are allowed'}
  # validates :salary ,numericality: true
  # validates :mobile ,numericality: {only_integer: true} ,length: {is: 10}
  # validates :email , format: {with: /\A[a-zA-Z0-9.]+@[a-zA-Z]+\.[a-zA-Z.]{3}+\z/ ,message: 'Format should match'}
  # validates :password, presence: true, confirmation: {message: "password didn't match"},length: {minimum: 8}
  # validates :confirm_password, presence: true,length: {minimum: 8}
end

Project/Rails_Proj/Hospital_Management/app/controllers/Api/V1/doctors_controller.rb
module Api
  module V1
    class DoctorsController < CustomController
      # before_action :authenticate_user

      #GET /doctors
      def index
        @doctors = Doctor.all
        render json: @doctors
      end

      #GET /doctor/:id
      def show
        @doctor = Doctor.find_by(id: params[:id])
        render json: {status: "SUCCESS", mesage: "Show Doctors", data: DoctorSerializer.new(@doctor)}, adapter: :json
      end

      #Post /doctors
      def create
        @doctor = Doctor.new(doctor_params)
        if @doctor.save
          render json: @doctor, adapter: :json, status: 201
        else
          render json: {error: 'Unable to create User.'}, status: 422
        end
      end

      def update
        @doctor = Doctor.find_by(id: params[:id])
        if @doctor
          @doctor.update(doctor_params)
          render json: {message: "User successfully updated."}, adapter: :json, status: 200
        else
          render json: {message: 'Unable to update user.'}, status: 422
        end
      end

      def destroy
        @doctor = Doctor.find_by(id: params[:id])
        if @doctor
          @doctor.destroy
          render json: {message: 'User successfully deleted.'}, status: 200
        else
          render json: {message: 'Unable to delete user.'}, status: 400
        end
      end

      private
      def doctor_params
        params.permit(:first_name, :last_name, :qualifications, :gender, :salary, :email , :mobile, :age , :password, :confirm_password, :comments ,:hospital_id)
      end

    end
  end
end

Project/Rails_Proj/Hospital_Management/app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :paginate
  helper_method :sort_column, :sort_direction
  DOCTOR_PER_PAGE = 17

  def new
    @doctor = Doctor.new
  end

  def paginate
    # debugger
    @page = params.fetch(:page,0).to_i
    # @page = params[:page] ? (params[:page].to_i) : 0
    if params[:search]
      @doctors = Doctor.all.offset(@page*DOCTOR_PER_PAGE).limit(DOCTOR_PER_PAGE).where("first_name ilike ? or last_name ilike ? or email ilike ? or qualifications ilike?", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%").order(sort_column + " " +sort_direction) #.order(params[:sort])
    else
      @doctors = Doctor.offset(@page*DOCTOR_PER_PAGE).limit(DOCTOR_PER_PAGE).order(sort_column + " " +sort_direction)
    end

    if params[:count]
      @count = params[:count].to_i
      if @count < Doctor.all.count
        @doctors = Doctor.limit(@count+2)
      else
        @doctors = Doctor.limit(@count)
      end
    end
  end

  def index
    @doctors = Doctor.limit(DOCTOR_PER_PAGE).offset(@page*DOCTOR_PER_PAGE).order(sort_column + " " +sort_direction)
  end

  def create
    doctor = Doctor.new doctor_params
    doctor.save
    redirect_to doctors_path
  end

  def show
    @doctor = Doctor.find_by(id: params[:id])
  end

  def edit
      @edit_doctor = Doctor.find_by(id: params[:id])
  end

  def update
    @edit_doctor = Doctor.find_by(id: params[:id])
    if @edit_doctor.update doctor_params
      redirect_to doctors_path
    end
  end

  def destroy
    doctor = Doctor.find_by(id: params[:id])
    doctor.destroy
    redirect_to doctors_path
  end

  def doctor_params
    params.require(:doctor).permit(:first_name, :last_name, :qualifications, :gender, :salary, :email , :mobile, :age , :password, :confirm_password, :comments ,:hospital_id,:avatar)
  end

  # def destroy_multiple
  #   Doctor.destroy(params[:doctors])
  #   flash.alert = "Are you sure want to delete these records"
  # end


  private
  def sort_column
    params[:sort] || "Salary"
  end

  def sort_direction
    params[:direction] || "asc"
  end
end

Project/Rails_Proj/Hospital_Management/app/helpers/doctors_helper.rb
module DoctorsHelper
  def sortable(column, title = nil)
     title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to column, :sort => column, :direction => direction
  end
end

Project/Rails_Proj/Hospital_Management/app/views/doctors/_doctors.html.erb
<div class="form-group">
  <%= form_tag doctor_paginate_path, method: 'get', remote: true do %>
    <%= text_field_tag :search, params[:search], class: "form-control w-25 ml-5"%>
    <%= submit_tag "Search", class: "btn btn-primary ml-5 mt-2 mix"%>
  <% end %>

  <p class="text-center">
    <%= link_to 'New |' ,'doctors/new'%>
     <%= link_to   params[:page] ? 'Previous Page | ': ' ' , doctor_paginate_path(page: @page-1), method: 'get', remote: true%>
     <%= link_to  "Next Page" , doctor_paginate_path(page: @page+1), method: 'get', remote: true%>
  </p>
</div>

<table>
  <tr>
    <th></th>
    <th><%= link_to "Id", :sort => "Id",remote: true%></th>
    <th><%= link_to "First_name", :sort => "First_name", remote: true%></th>
    <th><%= link_to "Last_name", :sort => "Last_name", remote: true %></th>
    <th>Qualifications</th>
    <th><%= sortable "Salary" %></th>
    <th>Email</th>
    <th>Mobile</th>
    <th>Age</th>
    <th>Hospital Id</th>
    <th>Show details</th>
    <th>Edit details</th>
    <th>Delete details</th>
  </tr>

<% @doctors.each do |d| %>
  <tr class="row-val">
    <th><%= check_box_tag "doctors[]",d.id %></th>
    <td><%= d.id %></td>
    <td><%= d.first_name %></td>
    <td><%= d.last_name %></td>
    <td><%= d.qualifications%></td>
    <td><%= d.salary %></td>
    <td><%= d.email %></td>
    <td><%= d.mobile %></td>
    <td><%= d.age %></td>
    <td><%= d.hospital_id %></td>
    <td><%= link_to 'Show' ,doctor_path(d) %></td>
    <td><%= link_to 'Edit' ,edit_doctor_path(d) %></td>
    <td><%= link_to 'Delete' ,doctor_path(d) ,
       method: :Delete ,
       data: {confirm: 'Are you certain?'}%></td>
  </tr>
<% end %>
</table>

Project/Rails_Proj/Hospital_Management/app/views/doctors/edit.html.erb
    <h1><center>Edit Doctor Information</center></h1>
      <%= form_for @edit_doctor do |d| %>
      <p>
        <%= d.label :First_name %><br>
        <%= d.text_field :first_name %>
      </p>

      <p>
        <%= d.label :Last_name %><br>
        <%= d.text_field :last_name %>
      </p>

      <p>
        <%= d.label :Qualifications %><br>
        <%= d.text_field :qualifications %>
      </p>

      <p>
        <%= d.label :Gender %><br>
        <%= d.text_field :gender %>
      </p>

      <p>
        <%= d.label :Salary %><br>
        <%= d.text_field :salary %>
      </p>

      <p>
        <%= d.label :Email %><br>
        <%= d.text_field :email %>
      </p>

      <p>
        <%= d.label :Mobile %><br>
        <%= d.text_field :mobile %>
      </p>

      <p>
        <%= d.label :Age %><br>
        <%= d.text_field :age %>
      </p>

      <p>
        <%= d.label :Hospital_id %><br>
        <%= d.text_field :hospital_id %>
      </p>

      <p>
        <%= d.label :Password %><br>
        <%= d.text_field :password %>
      </p>

      <p>
        <%= d.label :Confirm_Password %><br>
        <%= d.text_field :confirm_password %>
      </p>

      <p>
        <%= d.label :Comments %><br>
        <%= d.text_field :comments %>
      </p>

      <p>
        <%= d.submit%>
      </p>
    <% end %>

Project/Rails_Proj/Hospital_Management/app/views/doctors/index.html.erb
<h1>
  <strong>
    <center>List of Doctors</center>
  </strong>
</h1>

<div id="doctors-list" >
  <%= render partial: 'doctors'%>
</div>

<!-- <div class="x">
click me
</div>

<script type="text/javascript">
 console.log('hello')
  $('.x').click(()=>{

    alert("jquery")
  })
</script> -->

Project/Rails_Proj/Hospital_Management/app/views/doctors/new.html.erb
    <h1><center>Doctor Information</center></h1>

    <div class="input_field_wrapper">
      <div>
      <%= form_for @doctor ,html: {id:'myform',multipart: true}, url: doctors_path   do |d|  %>
          <%= d.label :fname , 'First Name' %><br>
          <%= d.text_field :first_name ,class:'form-control input', placeholder: 'Enter First Name',id:'fname' %>
          <small><p id = "firstname" class= "text-danger" >*Please enter valid name</p></small>

          <%= d.label :lname , 'Last Name' %><br>
          <%= d.text_field :last_name ,class:'form-control input', placeholder:'Enter Last Name' ,id:'lname'%>
          <small><p id = "lastname" class= "text-danger" >*Please enter valid name</p></small>

          <%= d.label :quali , 'Qualifications' %><br>
          <%= d.text_field :qualifications ,class:'form-control input', placeholder:'Enter Qualifications' ,id:'quali'%>

          <%= d.label :hid , 'Hospital Id' %><br>
          <%= d.text_field :hospital_id ,class:'form-control input', placeholder:'Enter Hospital Id' ,id:'hid'%>

          <%= d.label :gender , 'Gender' %><br>
          <%= d.text_field :gender ,class:'form-control input', placeholder:'Enter Gender' ,id:'gender'%>

          <%= d.label :salary , 'Salary' %><br>
          <%= d.text_field :salary ,class:'form-control input', placeholder:'Enter Salary' ,id:'salary'%>

          <%= d.label :email , 'Email' %><br>
          <%= d.text_field :email ,class:'form-control input', placeholder:'Enter Email' ,id:'email'%>
          <small><p id = 'mail' class= "text-danger" >*Email must contain @,.(xyz@gmail.com)</p></small>

           <%= d.submit class: "btn btn-primary" %>
      <% end %>
      <a href="javascript:void(0);" class="add_button" title="Add field">
        <button class=" btn btn-primary" style=" margin:5px;">Add More Field</button>
      </a>
    </div>
  </div>

Project/Rails_Proj/Hospital_Management/app/views/doctors/paginate.js.erb
$('#doctors-list').html('<%= escape_javascript(render partial: "doctors") %>')

 // $(window).scroll(function() {
 //      let windowRelativeBottom = $("#myElement")[0].getBoundingClientRect().bottom;
 //      if (windowRelativeBottom > $("#myElement")[0].clientHeight + 14) break;
 //      $('#doctors-list').append('<%= escape_javascript(render partial: "doctors") %>')
// });

Project/Rails_Proj/Hospital_Management/app/views/doctors/show.html.erb
<div class="text-right bg-secondary text-white">
  <%= link_to "Logout", doctor_logout_url, method: :get%>
</div>
<% if logged_in? %>
<div class="bg-secondary text-white">
  <h1><strong><center>Welcome Dr.<%= current_user.first_name %></center></strong></h1><hr>
</div>
  <div class="text-center font-weight-bold">
      Full Name:-<%= @doctor.first_name %>&nbsp;<%= @doctor.last_name %><br>
      Qualifications:-<%= @doctor.qualifications %><br>
      Email:-<%= @doctor.email %><br>
      Mobile Number:-<%= @doctor.mobile %><br>
      Hospital Id:-<%= @doctor.hospital_id%><br>
      Image:-<%= image_tag @doctor.avatar.url(:thumb) if @doctor.avatar? %>
  </div>

<%end%>