Project/Rails_Proj/Hospital_Management/config/routes.rb
Rails.application.routes.draw do
  get "login", to:"session#new", as: "doctor_login"
  post "login", to:"session#create"
  get "logout", to: "session#log_out", as: "doctor_logout"

  get 'department/show'
  root 'department#show'
  # get 'hospital/soft_delete/:id' =>'hospital#soft_delete'
  get "patient/:id/soft_delete", to:"patient#soft_delete", as: "patient_soft_delete"
  get "doctors/paginate", to:"doctors#paginate", as:"doctor_paginate"
  namespace :api do
    namespace :v1 do
      resources :doctors
      resources :hospital
      post 'doctor/login', to: 'session#login'
    end
  end
  resources :hospital, :doctors, :patient, :department, :appointments

end

Project/Rails_Proj/Hospital_Management/app/controllers/department_controller.rb
class DepartmentController < ApplicationController
  def show

  end
end

Project/Rails_Proj/Hospital_Management/app/helpers/department_helper.rb
module DepartmentHelper
end

Project/Rails_Proj/Hospital_Management/app/views/department/show.html.erb
<h1><strong><center>Hospital Management Database</center></strong></h1>
<table>
  <tr>
    <%= link_to 'Login', doctor_login_url%>
  </tr>
  <tr>
    <th>Tables</th>
    <th>Links</th>
  </tr>
  <tr>
    <td>Hospital Table</td>
    <td><%= link_to 'show',hospital_index_url%></td>
  </tr>
  <tr>
    <td>Patient Table</td>
    <td><%= link_to 'show',patient_index_url%></td>
  </tr>
  <tr>
    <td>Doctor Table</td>
    <td><%= link_to 'show',doctors_path%></td>
  </tr>
  <tr>
    <td>Medical Record Table</td>
    <td><%= link_to 'show',doctors_path%></td>
  </tr>
  <tr>
    <td>Appointments Table</td>
    <td><%= link_to 'show',appointments_path%></td>
  </tr>
</table>